In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"results.csv", encoding = "ISO-8859-1")

In [3]:
filt = df['HomeTeam'] == 'Arsenal'
filt2 = df['AwayTeam'] == 'Liverpool'
filt3 = df['Season'] > '2000-21'
TotalMatch = df[filt][filt2][filt3]
TotalMatch

/var/folders/fs/7xwm968n3gz7y_pc2ghf916c0000gn/T/ipykernel_74021/817409853.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  TotalMatch = df[filt][filt2][filt3]

,Season,DateTime,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
3420,2001-02,2002-01-13T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,4.0,2.0,3.0,1.0,15.0,16.0,1.0,1.0,0.0,0.0
3791,2002-03,2002-12-29T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,6.0,2.0,15.0,4.0,14.0,15.0,1.0,3.0,0.0,0.0
4272,2003-04,2004-04-09T00:00:00Z,Arsenal,Liverpool,4,2,H,1.0,2.0,A,...,7.0,5.0,2.0,8.0,16.0,9.0,3.0,1.0,0.0,0.0
4711,2004-05,2005-05-08T00:00:00Z,Arsenal,Liverpool,3,1,H,2.0,0.0,H,...,8.0,6.0,1.0,4.0,13.0,10.0,0.0,2.0,0.0,0.0
5008,2005-06,2006-03-12T00:00:00Z,Arsenal,Liverpool,2,1,H,1.0,0.0,H,...,4.0,3.0,5.0,0.0,8.0,18.0,0.0,2.0,0.0,1.0
5221,2006-07,2006-11-12T00:00:00Z,Arsenal,Liverpool,3,0,H,1.0,0.0,H,...,7.0,4.0,2.0,6.0,7.0,12.0,2.0,3.0,0.0,0.0
5804,2007-08,2008-04-05T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,1.0,A,...,6.0,4.0,5.0,3.0,10.0,10.0,1.0,2.0,0.0,0.0
6038,2008-09,2008-12-21T00:00:00Z,Arsenal,Liverpool,1,1,D,1.0,1.0,D,...,3.0,6.0,2.0,1.0,14.0,17.0,3.0,3.0,1.0,0.0
6490,2009-10,2010-02-10T00:00:00Z,Arsenal,Liverpool,1,0,H,0.0,0.0,D,...,6.0,7.0,3.0,6.0,19.0,13.0,3.0,2.0,0.0,0.0
6947,2010-11,2011-04-17T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,6.0,5.0,10.0,3.0,13.0,13.0,2.0,4.0,0.0,0.0
7013,2011-12,2011-08-20T00:00:00Z,Arsenal,Liverpool,0,2,A,0.0,0.0,D,...,6.0,8.0,9.0,5.0,11.0,6.0,2.0,2.0,1.0,0.0
7618,2012-13,2013-01-30T00:00:00Z,Arsenal,Liverpool,2,2,D,0.0,1.0,A,...,6.0,5.0,8.0,6.0,9.0,11.0,3.0,1.0,0.0,0.0
7854,2013-14,2013-11-02T00:00:00Z,Arsenal,Liverpool,2,0,H,1.0,0.0,H,...,7.0,4.0,3.0,5.0,11.0,7.0,2.0,1.0,0.0,0.0
8443,2014-15,2015-04-04T00:00:00Z,Arsenal,Liverpool,4,1,H,3.0,0.0,H,...,10.0,2.0,6.0,5.0,7.0,9.0,1.0,0.0,0.0,1.0
8553,2015-16,2015-08-24T00:00:00Z,Arsenal,Liverpool,0,0,D,0.0,0.0,D,...,5.0,8.0,7.0,8.0,2.0,13.0,1.0,4.0,0.0,0.0
8911,2016-17,2016-08-14T00:00:00Z,Arsenal,Liverpool,3,4,A,1.0,1.0,D,...,5.0,7.0,5.0,4.0,13.0,17.0,3.0,3.0,0.0,0.0
9464,2017-18,2017-12-22T00:00:00Z,Arsenal,Liverpool,3,3,D,0.0,1.0,A,...,4.0,9.0,7.0,8.0,9.0,11.0,1.0,0.0,0.0,0.0
9764,2018-19,2018-11-03T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,4.0,4.0,5.0,8.0,7.0,7.0,1.0,1.0,0.0,0.0
10398,2019-20,2020-07-15T20:15:00Z,Arsenal,Liverpool,2,1,H,2.0,1.0,H,...,2.0,8.0,2.0,13.0,14.0,10.0,3.0,1.0,0.0,0.0
10717,2020-21,2021-04-03T20:00:00Z,Arsenal,Liverpool,0,3,A,0.0,0.0,D,...,2.0,7.0,1.0,2.0,10.0,10.0,1.0,1.0,0.0,0.0
11086,2021-22,2022-03-16T20:15:00Z,Arsenal,Liverpool,0,2,A,0.0,0.0,D,...,2.0,3.0,1.0,6.0,9.0,9.0,0.0,1.0,0.0,0.0

In [4]:
# Home goal difference
TotalMatch['HGD'] = TotalMatch['FTHG'] - TotalMatch['FTAG']
# Home corner difference
TotalMatch['HCD'] = TotalMatch['HC'] - TotalMatch['AC']
# Home shot difference
TotalMatch['HSD'] = TotalMatch['HS'] - TotalMatch['AS']
# Home shot on target difference
TotalMatch['HSTD'] = TotalMatch['HST'] - TotalMatch['AST']
# Home foul difference
TotalMatch['HFD'] = TotalMatch['HF'] - TotalMatch['AF']
TotalMatch

,Season,DateTime,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AF,HY,AY,HR,AR,HGD,HCD,HSD,HSTD,HFD
3420,2001-02,2002-01-13T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,16.0,1.0,1.0,0.0,0.0,0,2.0,6.0,2.0,-1.0
3791,2002-03,2002-12-29T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,15.0,1.0,3.0,0.0,0.0,0,11.0,4.0,4.0,-1.0
4272,2003-04,2004-04-09T00:00:00Z,Arsenal,Liverpool,4,2,H,1.0,2.0,A,...,9.0,3.0,1.0,0.0,0.0,2,-6.0,0.0,2.0,7.0
4711,2004-05,2005-05-08T00:00:00Z,Arsenal,Liverpool,3,1,H,2.0,0.0,H,...,10.0,0.0,2.0,0.0,0.0,2,-3.0,0.0,2.0,3.0
5008,2005-06,2006-03-12T00:00:00Z,Arsenal,Liverpool,2,1,H,1.0,0.0,H,...,18.0,0.0,2.0,0.0,1.0,1,5.0,3.0,1.0,-10.0
5221,2006-07,2006-11-12T00:00:00Z,Arsenal,Liverpool,3,0,H,1.0,0.0,H,...,12.0,2.0,3.0,0.0,0.0,3,-4.0,-3.0,3.0,-5.0
5804,2007-08,2008-04-05T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,1.0,A,...,10.0,1.0,2.0,0.0,0.0,0,2.0,-3.0,2.0,0.0
6038,2008-09,2008-12-21T00:00:00Z,Arsenal,Liverpool,1,1,D,1.0,1.0,D,...,17.0,3.0,3.0,1.0,0.0,0,1.0,-4.0,-3.0,-3.0
6490,2009-10,2010-02-10T00:00:00Z,Arsenal,Liverpool,1,0,H,0.0,0.0,D,...,13.0,3.0,2.0,0.0,0.0,1,-3.0,2.0,-1.0,6.0
6947,2010-11,2011-04-17T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,13.0,2.0,4.0,0.0,0.0,0,7.0,3.0,1.0,0.0
7013,2011-12,2011-08-20T00:00:00Z,Arsenal,Liverpool,0,2,A,0.0,0.0,D,...,6.0,2.0,2.0,1.0,0.0,-2,4.0,-3.0,-2.0,5.0
7618,2012-13,2013-01-30T00:00:00Z,Arsenal,Liverpool,2,2,D,0.0,1.0,A,...,11.0,3.0,1.0,0.0,0.0,0,2.0,4.0,1.0,-2.0
7854,2013-14,2013-11-02T00:00:00Z,Arsenal,Liverpool,2,0,H,1.0,0.0,H,...,7.0,2.0,1.0,0.0,0.0,2,-2.0,0.0,3.0,4.0
8443,2014-15,2015-04-04T00:00:00Z,Arsenal,Liverpool,4,1,H,3.0,0.0,H,...,9.0,1.0,0.0,0.0,1.0,3,1.0,3.0,8.0,-2.0
8553,2015-16,2015-08-24T00:00:00Z,Arsenal,Liverpool,0,0,D,0.0,0.0,D,...,13.0,1.0,4.0,0.0,0.0,0,-1.0,4.0,-3.0,-11.0
8911,2016-17,2016-08-14T00:00:00Z,Arsenal,Liverpool,3,4,A,1.0,1.0,D,...,17.0,3.0,3.0,0.0,0.0,-1,1.0,-7.0,-2.0,-4.0
9464,2017-18,2017-12-22T00:00:00Z,Arsenal,Liverpool,3,3,D,0.0,1.0,A,...,11.0,1.0,0.0,0.0,0.0,0,-1.0,-3.0,-5.0,-2.0
9764,2018-19,2018-11-03T00:00:00Z,Arsenal,Liverpool,1,1,D,0.0,0.0,D,...,7.0,1.0,1.0,0.0,0.0,0,-3.0,-1.0,0.0,0.0
10398,2019-20,2020-07-15T20:15:00Z,Arsenal,Liverpool,2,1,H,2.0,1.0,H,...,10.0,3.0,1.0,0.0,0.0,1,-11.0,-21.0,-6.0,4.0
10717,2020-21,2021-04-03T20:00:00Z,Arsenal,Liverpool,0,3,A,0.0,0.0,D,...,10.0,1.0,1.0,0.0,0.0,-3,-1.0,-13.0,-5.0,0.0
11086,2021-22,2022-03-16T20:15:00Z,Arsenal,Liverpool,0,2,A,0.0,0.0,D,...,9.0,0.0,1.0,0.0,0.0,-2,-5.0,0.0,-1.0,0.0

In [5]:
# Win: 0, Draw: 1, Lose: 2

TotalMatch['FTR'] = TotalMatch['FTR'].replace(['H','D','A'], [0, 1, 2])
TotalMatch

,Season,DateTime,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AF,HY,AY,HR,AR,HGD,HCD,HSD,HSTD,HFD
3420,2001-02,2002-01-13T00:00:00Z,Arsenal,Liverpool,1,1,1,0.0,0.0,D,...,16.0,1.0,1.0,0.0,0.0,0,2.0,6.0,2.0,-1.0
3791,2002-03,2002-12-29T00:00:00Z,Arsenal,Liverpool,1,1,1,0.0,0.0,D,...,15.0,1.0,3.0,0.0,0.0,0,11.0,4.0,4.0,-1.0
4272,2003-04,2004-04-09T00:00:00Z,Arsenal,Liverpool,4,2,0,1.0,2.0,A,...,9.0,3.0,1.0,0.0,0.0,2,-6.0,0.0,2.0,7.0
4711,2004-05,2005-05-08T00:00:00Z,Arsenal,Liverpool,3,1,0,2.0,0.0,H,...,10.0,0.0,2.0,0.0,0.0,2,-3.0,0.0,2.0,3.0
5008,2005-06,2006-03-12T00:00:00Z,Arsenal,Liverpool,2,1,0,1.0,0.0,H,...,18.0,0.0,2.0,0.0,1.0,1,5.0,3.0,1.0,-10.0
5221,2006-07,2006-11-12T00:00:00Z,Arsenal,Liverpool,3,0,0,1.0,0.0,H,...,12.0,2.0,3.0,0.0,0.0,3,-4.0,-3.0,3.0,-5.0
5804,2007-08,2008-04-05T00:00:00Z,Arsenal,Liverpool,1,1,1,0.0,1.0,A,...,10.0,1.0,2.0,0.0,0.0,0,2.0,-3.0,2.0,0.0
6038,2008-09,2008-12-21T00:00:00Z,Arsenal,Liverpool,1,1,1,1.0,1.0,D,...,17.0,3.0,3.0,1.0,0.0,0,1.0,-4.0,-3.0,-3.0
6490,2009-10,2010-02-10T00:00:00Z,Arsenal,Liverpool,1,0,0,0.0,0.0,D,...,13.0,3.0,2.0,0.0,0.0,1,-3.0,2.0,-1.0,6.0
6947,2010-11,2011-04-17T00:00:00Z,Arsenal,Liverpool,1,1,1,0.0,0.0,D,...,13.0,2.0,4.0,0.0,0.0,0,7.0,3.0,1.0,0.0
7013,2011-12,2011-08-20T00:00:00Z,Arsenal,Liverpool,0,2,2,0.0,0.0,D,...,6.0,2.0,2.0,1.0,0.0,-2,4.0,-3.0,-2.0,5.0
7618,2012-13,2013-01-30T00:00:00Z,Arsenal,Liverpool,2,2,1,0.0,1.0,A,...,11.0,3.0,1.0,0.0,0.0,0,2.0,4.0,1.0,-2.0
7854,2013-14,2013-11-02T00:00:00Z,Arsenal,Liverpool,2,0,0,1.0,0.0,H,...,7.0,2.0,1.0,0.0,0.0,2,-2.0,0.0,3.0,4.0
8443,2014-15,2015-04-04T00:00:00Z,Arsenal,Liverpool,4,1,0,3.0,0.0,H,...,9.0,1.0,0.0,0.0,1.0,3,1.0,3.0,8.0,-2.0
8553,2015-16,2015-08-24T00:00:00Z,Arsenal,Liverpool,0,0,1,0.0,0.0,D,...,13.0,1.0,4.0,0.0,0.0,0,-1.0,4.0,-3.0,-11.0
8911,2016-17,2016-08-14T00:00:00Z,Arsenal,Liverpool,3,4,2,1.0,1.0,D,...,17.0,3.0,3.0,0.0,0.0,-1,1.0,-7.0,-2.0,-4.0
9464,2017-18,2017-12-22T00:00:00Z,Arsenal,Liverpool,3,3,1,0.0,1.0,A,...,11.0,1.0,0.0,0.0,0.0,0,-1.0,-3.0,-5.0,-2.0
9764,2018-19,2018-11-03T00:00:00Z,Arsenal,Liverpool,1,1,1,0.0,0.0,D,...,7.0,1.0,1.0,0.0,0.0,0,-3.0,-1.0,0.0,0.0
10398,2019-20,2020-07-15T20:15:00Z,Arsenal,Liverpool,2,1,0,2.0,1.0,H,...,10.0,3.0,1.0,0.0,0.0,1,-11.0,-21.0,-6.0,4.0
10717,2020-21,2021-04-03T20:00:00Z,Arsenal,Liverpool,0,3,2,0.0,0.0,D,...,10.0,1.0,1.0,0.0,0.0,-3,-1.0,-13.0,-5.0,0.0
11086,2021-22,2022-03-16T20:15:00Z,Arsenal,Liverpool,0,2,2,0.0,0.0,D,...,9.0,0.0,1.0,0.0,0.0,-2,-5.0,0.0,-1.0,0.0

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score, confusion_matrix, roc_auc_score, classification_report, log_loss

from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression

In [7]:
features = TotalMatch[['HCD', 'HSD', 'HSTD', 'HFD']]
target = TotalMatch['FTR']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(features, target, test_size=0.3, stratify = target)

In [9]:
names = ["Nearest Neighbors", "Logistic Regression","Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "QDA"]

classifiers = [
    KNeighborsClassifier(3),
    LogisticRegression(),
    SVC(kernel="linear", C=0.025, probability=True),
    SVC(gamma=2, C=1, probability=True),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

In [10]:
for name, clf in zip(names, classifiers):
        clf.fit(X_train, y_train)
        accuracy = clf.score(X_test, y_test)

        # prediction_proba = clf.predict_proba(X_test)
        # logloss = log_loss(y_test,prediction_proba)
        # precision, recall, fscore, support = score(y_test, prediction)
        # conf_martrix = confusion_matrix(y_test, prediction)
        # clas_report = classification_report(y_test, prediction)

        print(name, accuracy)

Nearest Neighbors 0.42857142857142855
Logistic Regression 0.42857142857142855
Linear SVM 0.7142857142857143
RBF SVM 0.42857142857142855
Gaussian Process 0.5714285714285714
Decision Tree 0.7142857142857143
Random Forest 0.42857142857142855
Neural Net 0.42857142857142855
AdaBoost 0.42857142857142855
Naive Bayes 0.42857142857142855
QDA 0.42857142857142855

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")